# Site settings
highlighter: pygments
title: "蒲公英"
email: yanlei_man@outlook.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://hashcode12.github.io/"
title_description: "业精于勤，行成于思"
title_image: "%E5%A4%B4%E5%83%8F.jpeg"
google_analytics: "UA-20365477-3"
disqus_account: cartenoire
github_repository: https://github.com/hashcode12/hashcode12.github.com
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 风雪初现
github_username:  hashcode12
linkedin_link: http://www.linkedin.com/in/%E5%BB%B6%E7%A3%8A-%E5%BC%A0-421500113?trk=hp-identity-name
google_plus_link: https://plus.google.com/u/0/116743709485113437459
stackoverflow_link: https://www.baidu.com/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/Yanlei_Hello\">风雪初现</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/hashcode12/hashcode12.github.com\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
